name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  make-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Generate by type
        uses: kerry-patrick-il/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: diagram_type.svg
      - name: Generate by number of changes
        uses: kerry-patrick-il/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: diagram_num_changes.svg
          color_encoding: "number-of-changes"
      - name: Generate by latest changes
        uses: kerry-patrick-il/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: diagram_last_change.svg
          color_encoding: "last-change"

